---
title: Jimmy Young
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
version: v1
description:
baseurl:
url: jyng.github.io
twitter: _jyngo
github: https://github.com/jyng
dribbble: https://dribbble.com/jyng
arena: https://are.na/earth-person
linkedin: youngjimmy
instagram: https://instagram.com/earthperson
email: jyng02@gmail.com
resume: https://dropbox.com/
tv: 4.9.0
permalink: "/:title"
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
gems:
- jekyll-seo-tag
