title: "Jimmy's Portfolio"
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm Jimmy Young. Digital Product Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: https://jyngo.me/

twitter_username: _jyngo
github_username: jyngo
dribbble_username: jyngo

permalink: /:title


#Build settings
markdown: kramdown
